### ISSUE TITLE
ModuleNotFoundError: No module named 'SearchEngines'

### ISSUE THREAD

**Issue by shubhamsingh987** [fs0c131y/AadhaarSearchEngine#12]

**Comment by binora** [comment]
You need to run it with Python 2.7. That worked for me.

**Comment by harsh-pawar-544** [comment]
I am running it on Python 2.7.17 but still not working

**Comment by ghost** [comment]
replace SearchEngines  with AadhaarSearchEngine.comman.SearchEngine and them replace` iter() `with `__iter__()` on the same file.

**Comment by prakhar897** [comment]
make a pr dude
