### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by RishabhTayal** [fs0c131y/AadhaarSearchEngine#2]
Can you add more docs on how to install it? There are some python noobs out there (like me 😉) who don't know how to install the tool.

**Comment by RuthlessRuler** [comment]
Well, those noobs should first learn to use Google instead of making an Issue on repository on GitHub.

Also, please refrain on using Issues as how to do questions as it's pretty much plain English when it says "Issues".

**Comment by RishabhTayal** [comment]
@RuthlessRuler No need to be sassy and rude here. Using issues for asking questions is a known practice on Github. I opened the issue so the developer can update the README.md doc to make it more easy to understand.

**Comment by RuthlessRuler** [comment]
Well, the type of questions you are asking can be easily found if you know how to use a search engine. No developer puts on how you install some basic python stuff.

It's just you who is being so childish(and dumb)and not me being "sassy". 

It's expected if you are looking at python repository, you know what to do and what not do.
And well its not being rude it's being blunt and direct. This is not the place for your how to do stuff.

**Comment by RishabhTayal** [comment]
Going to close this since it was implement in https://github.com/fs0c131y/AadhaarSearchEngine/pull/4. Thanks @mzfr 👍
